// components/Layout.vue
<template>
  <div class="layout">
    <!-- Sidebar -->
    <aside class="sidebar">
      <div class="sidebar-header">
        <el-icon><DataLine /></el-icon>
        <span>蓝鲸平台运维工具</span>
      </div>

      <el-menu
        :default-openeds="['ops', 'agent']"
        :default-active="currentRoute"
        class="sidebar-menu"
        background-color="#1a2b42"
        text-color="#94a3b8"
        active-text-color="#ffffff"
        @select="handleMenuSelect"
      >
        <el-sub-menu index="ops">
          <template #title>
            <el-icon><Monitor /></el-icon>
            <span>蓝鲸平台运维</span>
          </template>
          <el-menu-item :index="ViewId.DAILY_INSPECTION">
            <span class="menu-dot" :class="{ active: currentRoute === ViewId.DAILY_INSPECTION }"></span>
            日常巡检
          </el-menu-item>
          <el-menu-item :index="ViewId.OPERATION_VIEW">
            <span class="menu-dot" :class="{ active: currentRoute === ViewId.OPERATION_VIEW }"></span>
            运行视图
          </el-menu-item>
          <el-menu-item :index="ViewId.ALARM_QUERY">
            <span class="menu-dot" :class="{ active: currentRoute === ViewId.ALARM_QUERY }"></span>
            告警查询
          </el-menu-item>
        </el-sub-menu>
        <el-sub-menu index="agent">
          <template #title>
            <el-icon><ShieldCheck /></el-icon>
            <span>蓝鲸Agent检查</span>
          </template>
          <el-menu-item :index="ViewId.AGENT_STATUS">
            <span class="menu-dot" :class="{ active: currentRoute === ViewId.AGENT_STATUS }"></span>
            agent状态检查
          </el-menu-item>
          <el-menu-item :index="ViewId.SCRIPT_EXEC">
            <span class="menu-dot" :class="{ active: currentRoute === ViewId.SCRIPT_EXEC }"></span>
            脚本执行检查
          </el-menu-item>
        </el-sub-menu>
      </el-menu>

      <div class="sidebar-footer">
        <div class="user-info">
          <div class="user-avatar">
            <el-icon><User /></el-icon>
          </div>
          <div class="user-details">
            <p class="user-name">Admin User</p>
            <p class="user-role">System Admin</p>
          </div>
          <el-button
            type="danger"
            :icon="SwitchButton"
            circle
            size="small"
            @click="$emit('logout')"
            title="退出登录"
          />
        </div>
      </div>
    </aside>

    <!-- Main Content Area -->
    <div class="main-area">
      <!-- Top Header -->
      <header class="top-header">
        <h1 class="breadcrumb">{{ breadcrumb }}</h1>
        <div class="header-actions">
          <div class="status-badge">
            <span class="status-dot"></span>
            System Operational
          </div>
          <el-divider direction="vertical" />
          <el-badge :value="3" :max="99">
            <el-button :icon="Bell" circle />
          </el-badge>
        </div>
      </header>

      <!-- Page Content -->
      <main class="page-content">
        <slot></slot>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { 
  Monitor, 
  DataLine, 
  User, 
  Bell, 
  SwitchButton 
} from '@element-plus/icons-vue';
import { ViewId } from '../types';

// ShieldCheck is not in element-plus icons, we'll use a different icon
const ShieldCheck = Monitor;

defineEmits<{
  logout: []
}>();

const router = useRouter();
const route = useRoute();

const currentRoute = computed(() => route.name as string);

const menuConfig = [
  {
    id: 'ops',
    label: '蓝鲸平台运维',
    children: [
      { id: ViewId.DAILY_INSPECTION, label: '日常巡检' },
      { id: ViewId.OPERATION_VIEW, label: '运行视图' },
      { id: ViewId.ALARM_QUERY, label: '告警查询' },
    ]
  },
  {
    id: 'agent',
    label: '蓝鲸Agent检查',
    children: [
      { id: ViewId.AGENT_STATUS, label: 'agent状态检查' },
      { id: ViewId.SCRIPT_EXEC, label: '脚本执行检查' },
    ]
  }
];

const breadcrumb = computed(() => {
  for (const menu of menuConfig) {
    const found = menu.children?.find(c => c.id === currentRoute.value);
    if (found) {
      return `${menu.label} / ${found.label}`;
    }
  }
  return 'Dashboard';
});

const handleMenuSelect = (index: string) => {
  router.push(`/${index}`);
};
</script>

<style scoped>
.layout {
  display: flex;
  height: 100vh;
  overflow: hidden;
  background: #f1f5f9;
}

.sidebar {
  width: 256px;
  background: #1a2b42;
  color: #94a3b8;
  display: flex;
  flex-direction: column;
  box-shadow: 4px 0 6px -1px rgba(0, 0, 0, 0.1);
  z-index: 20;
}

.sidebar-header {
  height: 56px;
  display: flex;
  align-items: center;
  padding: 0 16px;
  background: #142233;
  border-bottom: 1px solid #334155;
  font-weight: bold;
  color: white;
  letter-spacing: 0.5px;
  gap: 8px;
}

.sidebar-header .el-icon {
  color: #60a5fa;
  font-size: 20px;
}

.sidebar-menu {
  flex: 1;
  overflow-y: auto;
  border-right: none;
  padding: 16px 0;
}

.sidebar-menu :deep(.el-sub-menu__title) {
  font-weight: 500;
}

.sidebar-menu :deep(.el-menu-item) {
  padding-left: 48px !important;
}

.sidebar-menu :deep(.el-menu-item.is-active) {
  background: #2563eb !important;
}

.menu-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #64748b;
  margin-right: 8px;
  display: inline-block;
}

.menu-dot.active {
  background: white;
}

.sidebar-footer {
  padding: 16px;
  background: #142233;
  border-top: 1px solid #334155;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 12px;
}

.user-avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: #1e40af;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  border: 1px solid #3b82f6;
}

.user-details {
  flex: 1;
  min-width: 0;
}

.user-name {
  font-size: 14px;
  font-weight: 500;
  color: white;
  margin: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.user-role {
  font-size: 12px;
  color: #94a3b8;
  margin: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.main-area {
  flex: 1;
  display: flex;
  flex-direction: column;
  height: 100vh;
  overflow: hidden;
}

.top-header {
  height: 56px;
  background: white;
  border-bottom: 1px solid #e2e8f0;
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 24px;
  z-index: 10;
}

.breadcrumb {
  font-size: 18px;
  font-weight: bold;
  color: #1e293b;
  margin: 0;
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 16px;
  font-size: 14px;
}

.status-badge {
  display: flex;
  align-items: center;
  gap: 8px;
  color: #64748b;
  background: #f1f5f9;
  padding: 6px 12px;
  border-radius: 9999px;
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #22c55e;
  animation: pulse 2s infinite;
}

@keyframes pulse {
  0%, 100% {
    opacity: 1;
  }
  50% {
    opacity: 0.5;
  }
}

.page-content {
  flex: 1;
  overflow: auto;
  background: #f3f5f8;
  padding: 0;
}
</style>

// components/Layout.tsx
import React from 'react';
import { ViewId, MenuItem } from '../types';
import { 
  Monitor, 
  ShieldCheck, 
  Activity, 
  List, 
  Bell, 
  Terminal, 
  ChevronDown, 
  ChevronRight,
  LogOut,
  User
} from 'lucide-react';

interface LayoutProps {
  currentView: ViewId;
  onNavigate: (view: ViewId) => void;
  onLogout: () => void;
  children: React.ReactNode;
}

const MENU_ITEMS: MenuItem[] = [
  {
    id: 'ops',
    label: '蓝鲸平台运维',
    icon: <Monitor size={18} />,
    children: [
      { id: ViewId.DAILY_INSPECTION, label: '日常巡检' },
      { id: ViewId.OPERATION_VIEW, label: '运行视图' },
      { id: ViewId.ALARM_QUERY, label: '告警查询' },
    ]
  },
  {
    id: 'agent',
    label: '蓝鲸Agent检查',
    icon: <ShieldCheck size={18} />,
    children: [
      { id: ViewId.AGENT_STATUS, label: 'agent状态检查' },
      { id: ViewId.SCRIPT_EXEC, label: '脚本执行检查' },
    ]
  }
];

export const Layout: React.FC<LayoutProps> = ({ currentView, onNavigate, onLogout, children }) => {
  const [expandedMenus, setExpandedMenus] = React.useState<string[]>(['ops', 'agent']);

  const toggleMenu = (menuId: string) => {
    setExpandedMenus(prev => 
      prev.includes(menuId) ? prev.filter(id => id !== menuId) : [...prev, menuId]
    );
  };

  const getBreadcrumb = () => {
    for (const menu of MENU_ITEMS) {
      const found = menu.children?.find(c => c.id === currentView);
      if (found) {
        return `${menu.label} / ${found.label}`;
      }
    }
    return 'Dashboard';
  };

  return (
    <div className="flex h-screen bg-slate-100 overflow-hidden">
      
      {/* Sidebar */}
      <aside className="w-64 bg-[#1a2b42] text-slate-300 flex flex-col shadow-xl z-20">
        <div className="h-14 flex items-center px-4 bg-[#142233] border-b border-slate-700 font-bold text-white tracking-wide">
          <Activity className="mr-2 text-blue-400" /> 蓝鲸平台运维工具
        </div>

        <div className="flex-1 overflow-y-auto py-4">
          <nav className="space-y-1 px-2">
            {MENU_ITEMS.map((menu) => (
              <div key={menu.id}>
                <button 
                  onClick={() => toggleMenu(menu.id)}
                  className="w-full flex items-center justify-between px-3 py-2.5 text-sm font-medium rounded-md hover:bg-slate-700/50 hover:text-white transition-colors group"
                >
                  <div className="flex items-center">
                    <span className="mr-3 group-hover:text-blue-400 transition-colors">{menu.icon}</span>
                    {menu.label}
                  </div>
                  {expandedMenus.includes(menu.id) ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                </button>

                {/* Submenu */}
                {expandedMenus.includes(menu.id) && (
                  <div className="mt-1 space-y-1 pl-10 pr-2">
                    {menu.children?.map((child) => (
                      <button
                        key={child.id}
                        onClick={() => onNavigate(child.id)}
                        className={`w-full flex items-center px-3 py-2 text-sm rounded-md transition-all duration-200
                          ${currentView === child.id 
                            ? 'bg-blue-600 text-white shadow-md' 
                            : 'text-slate-400 hover:text-white hover:bg-slate-700/30'
                          }`}
                      >
                        <span className={`w-1.5 h-1.5 rounded-full mr-2 ${currentView === child.id ? 'bg-white' : 'bg-slate-500'}`}></span>
                        {child.label}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </nav>
        </div>

        <div className="p-4 bg-[#142233] border-t border-slate-700">
           <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-blue-800 flex items-center justify-center text-white border border-blue-600">
                 <User size={16} />
              </div>
              <div className="flex-1 min-w-0">
                 <p className="text-sm font-medium text-white truncate">Admin User</p>
                 <p className="text-xs text-slate-400 truncate">System Admin</p>
              </div>
              <button onClick={onLogout} className="text-slate-400 hover:text-red-400 transition-colors" title="Logout">
                 <LogOut size={18} />
              </button>
           </div>
        </div>
      </aside>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col h-screen overflow-hidden">
        
        {/* Top Header */}
        <header className="h-14 bg-white border-b border-slate-200 shadow-sm flex items-center justify-between px-6 z-10">
          <h1 className="text-lg font-bold text-slate-800 flex items-center">
            {getBreadcrumb()}
          </h1>
          <div className="flex items-center gap-4 text-sm">
             <div className="hidden md:flex items-center gap-2 text-slate-500 bg-slate-100 px-3 py-1.5 rounded-full">
                <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
                System Operational
             </div>
             <div className="h-6 w-px bg-slate-300"></div>
             <button className="text-slate-500 hover:text-blue-600 relative">
               <Bell size={20} />
               <span className="absolute -top-1 -right-1 w-2.5 h-2.5 bg-red-500 rounded-full border-2 border-white"></span>
             </button>
          </div>
        </header>

        {/* Page Content */}
        <main className="flex-1 overflow-auto bg-[#f3f5f8] p-0">
           {/* We pass children here */}
           <div className="min-h-full">
             {children}
           </div>
        </main>
      </div>

    </div>
  );
};
